### ISSUE TITLE
Just a little suggestions from your friends! 😄

### ISSUE THREAD

**Issue by andrianarivo** [tumainimaganiko/Vehicle-Company#2]
Hi @tumainimaganiko, good job so far on the Portfolio project. Below are some ideas and suggestions about the project, cheers! 👍🏽

HIGHLIGHTS 🎯

- The project is well structured and organised into folders/directories ✅
- The project has a comprehensive README documentation ✅
- The project has been deployed properly and is accessible viewed via the demo link provided ✅

RECOMMENDATIONS 🤔

- Help the project to be readable and easy to maintain by adding descriptive comments in your files 🥇
- Use containers to help your design support a wide variety of screens. (responsiveness) 👩🏻‍💻
- Show 2 participants in the mobile version, and when the user clicks on the more button, show all the participants. Otherwise, hide the button.  🥳
- We think you should add more effort to your About page's heading section. Add some padding for the mobile version. 🤩

**Comment by tumainimaganiko** [comment]
Hi, @andrianarivo 👋, I've received your suggestion’s with an open heart and I have tried to implement all  Suggestions . Hopefully, the project now appears well. feel free to open another issue if you find anything.
